// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Qa4UPHrOHI47q6DbjXXxku7sdL9dZ7U',
    appId: '1:954899354342:android:eaf083c38d474d98aaa127',
    messagingSenderId: '954899354342',
    projectId: 'my-chat-ab433',
    storageBucket: 'my-chat-ab433.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqEZDrtt-7cZzX8zpfeYP4UiBYoZWdvE',
    appId: '1:954899354342:web:c911e3d7e45539cfaaa127',
    messagingSenderId: '954899354342',
    projectId: 'my-chat-ab433',
    authDomain: 'my-chat-ab433.firebaseapp.com',
    storageBucket: 'my-chat-ab433.firebasestorage.app',
    measurementId: 'G-VG34TZKQKS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTqEZDrtt-7cZzX8zpfeYP4UiBYoZWdvE',
    appId: '1:954899354342:web:7e30d3fe6a7b0375aaa127',
    messagingSenderId: '954899354342',
    projectId: 'my-chat-ab433',
    authDomain: 'my-chat-ab433.firebaseapp.com',
    storageBucket: 'my-chat-ab433.firebasestorage.app',
    measurementId: 'G-VBWV0D1T8F',
  );

}